services:
  grafana:
    user: root
    container_name: openweather-datasource
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    
    ports:
      - 3001:3000/tcp
    
    volumes:
      - ./dist:/var/lib/grafana/plugins/openweather-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/openweather-datasource
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.openweather-datasource:debug
      GF_LOG_LEVEL: debug
      GF_PATHS_PLUGINS: /var/lib/grafana/plugins
